application/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.sitemaps.views import sitemap
from django.http.response import HttpResponse

from application import views as app_view
from application.constants import CONSPECTS
from application.sitemap import ApplicationSitemap, ConspectsSitemap

from blog import urls as blog_urls
from blog.sitemaps import BlogSitemap
from cars import urls as cars_urls
from fileuploader import urls as fileuploader_urls
from metrics import urls as metric_urls
from resume import urls as resume_urls


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {
            "sitemaps": {
                "main": ApplicationSitemap,
                "blog": BlogSitemap,
                "conspects": ConspectsSitemap,
            }
        },
        "sitemap_xml"),
    url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-Agent: *\nDisallow: \nHost: ilnurgi1.ru\n",
            content_type="text/plain")),
    url(
        r'^admin/',
        include(admin.site.urls)),
    url(
        r'^blog/',
        include(blog_urls, namespace='blog')),
    url(
        r'^fileuploader/',
        include(fileuploader_urls, namespace='fileuploader')),
    url(
        r'^sitemap/',
        app_view.SiteMap.as_view(), name='sitemap'),
    url(
        r'^metrics/',
        include(metric_urls, namespace='metrics')),
    url(
        r'^conspects/$',
        app_view.ConspectsPage.as_view(),
        name='conspects_page'),
    url(
        r'^cars/',
        include(cars_urls, namespace='cars')),
    url(
        r'^login/',
        login,
        {
            "template_name": "application/login.html",
            "extra_context": {
                "conspects": CONSPECTS,
            }
        },
        'login'),
    url(
        r'^logout/',
        logout,
        {
            "next_page": "resume:home_page"
        },
        'logout'),
    url(
        r'^$',
        include(resume_urls, namespace="resume")),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blog/urls.py
# coding: utf-8

from django.conf.urls import url

from blog import views

urlpatterns = [

    url(
        r'comment_create/(?P<post_slug>.+)',
        views.comment_create,
        name='comment_create'),
    url(
        r'post/create',
        views.PostCreateView.as_view(),
        name='post_create'),
    url(
        r'post/edit/(?P<slug>.+)',
        views.PostUpdateView.as_view(),
        name='post_update'),
    url(
        r'post/delete/(?P<slug>.+)',
        views.PostDeleteView.as_view(),
        name='post_delete'),
    url(
        r'(?P<category_name>\w*)/(?P<slug>.+)',
        views.PostDetailView.as_view(),
        name='post_detail'),
    url(
        r'(?P<category_name>\w*)$',
        views.PostListView.as_view(),
        name='list'),
]

ilnurgi/ilnurgi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ilnurgi import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', include(admin.site.urls))
]

resume/urls.py
# coding: utf-8

from django.conf.urls import url

from resume import views

urlpatterns = [
    url(
        r'',
        views.HomePage.as_view(),
        name='home_page'),
]

application/views.py
# coding: utf-8

from django.views.generic import TemplateView

from application.constants import CONSPECTS
from blog.models import Category


class ConspectsMixin(object):

    def get_context_data(self, **kwargs):
        context = super(ConspectsMixin, self).get_context_data(**kwargs)
        context['conspects'] = CONSPECTS
        return context


class SiteMap(ConspectsMixin, TemplateView):
    template_name = 'application/sitemap.html'

    def get_context_data(self, **kwargs):
        context = super(SiteMap, self).get_context_data(**kwargs)

        context['active_page'] = 'sitemap'

        categories = Category.objects
        if not self.request.user.is_superuser:
            categories = categories.filter(post__published=True)
        context['categories'] = categories.all()
        return context


class ConspectsPage(ConspectsMixin, TemplateView):
    template_name = 'application/conspects.html'

application/templates/base.html
{%  comment %}
xs - <  768px;
sm - >  768px;
md - >= 992px;
lg - >= 1200px;
{% endcomment %}
{% load static %}
{% get_static_prefix as STATIC_URL %}

<!DOCTYPE html>

<html>

    <head>
        <meta
                name="google-site-verification"
                content="{{ GOOGLE_SITE_VERIFICATIN }}" />

        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block description %}
{#            <meta name="description" content="">#}
        {% endblock %}

        <script src="{{ STATIC_URL }}jquery-2.1.4.min.js"></script>

        <!-- Latest compiled and minified CSS -->
        <link
                rel="stylesheet"
                href="{{ STATIC_URL }}bootstrap/3.3.5/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link
                rel="stylesheet"
                href="{{ STATIC_URL }}bootstrap/3.3.5/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="{{ STATIC_URL }}bootstrap/3.3.5/js/bootstrap.min.js"></script>

        {% block extra_head %}{% endblock %}

        <link
                rel="stylesheet"
                href="{{ STATIC_URL }}application.css">

        <link rel="alternate" hreflang="ru">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>

        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button
                                type="button"
                                class="navbar-toggle collapsed"
                                data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1"
                                aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Главная</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div
                            class="collapse navbar-collapse"
                            id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li
                                {% if active_page == "blog" %}
                                    class="active"
                                {% endif %}>
                                <a href="{% url "blog:list" "" %}">
                                    Блог
                                </a>
                            </li>
                            <li class="dropdown">
                                <a
                                    href="#"
                                    class="dropdown-toggle"
                                    data-toggle="dropdown"
                                    role="button"
                                    aria-haspopup="true"
                                    aria-expanded="false">

                                    Конспекты
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    {% for conspect_items in conspects %}
                                        {% for conspect in conspect_items %}
                                            <li><a href="{{ conspect.url }}">{{ conspect.title }}</a></li>
                                        {% endfor %}
                                        <li role="separator" class="divider"></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li
                                {% if active_page == 'metrics' %}
                                    class="active"
                                {% endif %}>
                                <a href="{% url 'metrics:home_page' %}">
                                    Статистика
                                </a>
                            </li>
                            <li
                                {% if active_page == 'sitemap' %}
                                    class="active"
                                {% endif %}>
                                <a href="{% url 'sitemap' %}">
                                    Карта
                                </a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if view.request.user.is_superuser %}
                                <li
                                    {% if active_page == 'fileuploader' %}
                                        class="active"
                                    {% endif %}>
                                    <a href="{% url 'fileuploader:home_page' %}">
                                        Файлохранилище
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'admin:index' %}">
                                        Админка
                                    </a>
                                </li>
                            {% endif %}
                            {% if view.request.user.is_superuser %}
                                <li><a href="{% url 'logout' %}">Выйти</a></li>
                            {% else %}
                                <li><a href="{% url 'login' %}">Войти</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        {% block extra_body %}{% endblock %}
    </body>

</html>