application/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.sitemaps.views import sitemap
from django.http.response import HttpResponse

from application import views as app_view
from application.constants import CONSPECTS
from application.sitemap import ApplicationSitemap, ConspectsSitemap

from blog import urls as blog_urls
from blog.sitemaps import BlogSitemap
from cars import urls as cars_urls
from fileuploader import urls as fileuploader_urls
from metrics import urls as metric_urls
from resume import urls as resume_urls


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {
            "sitemaps": {
                "main": ApplicationSitemap,
                "blog": BlogSitemap,
                "conspects": ConspectsSitemap,
            }
        },
        "sitemap_xml"),
    url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-Agent: *\nDisallow: \nHost: ilnurgi1.ru\n",
            content_type="text/plain")),
    url(
        r'^admin/',
        include(admin.site.urls)),
    url(
        r'^blog/',
        include(blog_urls, namespace='blog')),
    url(
        r'^fileuploader/',
        include(fileuploader_urls, namespace='fileuploader')),
    url(
        r'^sitemap/',
        app_view.SiteMap.as_view(), name='sitemap'),
    url(
        r'^metrics/',
        include(metric_urls, namespace='metrics')),
    url(
        r'^conspects/$',
        app_view.ConspectsPage.as_view(),
        name='conspects_page'),
    url(
        r'^cars/',
        include(cars_urls, namespace='cars')),
    url(
        r'^login/',
        login,
        {
            "template_name": "application/login.html",
            "extra_context": {
                "conspects": CONSPECTS,
            }
        },
        'login'),
    url(
        r'^logout/',
        logout,
        {
            "next_page": "resume:home_page"
        },
        'logout'),
    url(
        r'^$',
        include(resume_urls, namespace="resume")),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blog/urls.py
# coding: utf-8

from django.conf.urls import url

from blog import views

urlpatterns = [

    url(
        r'comment_create/(?P<post_slug>.+)',
        views.comment_create,
        name='comment_create'),
    url(
        r'post/create',
        views.PostCreateView.as_view(),
        name='post_create'),
    url(
        r'post/edit/(?P<slug>.+)',
        views.PostUpdateView.as_view(),
        name='post_update'),
    url(
        r'post/delete/(?P<slug>.+)',
        views.PostDeleteView.as_view(),
        name='post_delete'),
    url(
        r'(?P<category_name>\w*)/(?P<slug>.+)',
        views.PostDetailView.as_view(),
        name='post_detail'),
    url(
        r'(?P<category_name>\w*)$',
        views.PostListView.as_view(),
        name='list'),
]

ilnurgi/ilnurgi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ilnurgi import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', include(admin.site.urls))
]

blog/models.py
# coding: utf-8

import re

from io import StringIO
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

from markdown import markdown

from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter

from pytils.translit import slugify

import lxml.html as html


class Category(models.Model):

    name = models.CharField(u'Name', max_length=50, unique=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Post(models.Model):

    title = models.CharField(u'Post title', max_length=100)
    raw_content = models.TextField(u'Post raw content')
    content = models.TextField(u'Post content')
    published = models.BooleanField(default=False)
    category = models.ForeignKey(Category)

    created = models.DateTimeField(u'Post created date', auto_now_add=True)
    modified = models.DateTimeField(u'Post modified date', auto_now=True)

    slug = models.SlugField(blank=True, unique=True)

    description = models.CharField(u'Description', max_length=255)

    re_references = re.compile(u'\[(.+?)\]\[(.+?)\]')
    re_files = re.compile(u'(\[FILE=(\d+)\])')

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.category.name, self.slug])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.content = (
            self.set_tables_classes(
                self.add_files(
                    self.add_code_style(
                        markdown(
                            self.add_url_references(
                                self.raw_content),
                            extensions=['tables']
                        )))))
        self.slug = slugify(self.title)

        super(Post, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)

    def add_files(self, content):
        finds = self.re_files.findall(content)
        file_ids = [int(file_id) for _, file_id in finds]
        file_ids_map = {
            f.id: f for f in File.objects.filter(id__in=file_ids)
        }
        for replacer, file_id in finds:
            f = file_ids_map.get(int(file_id))
            if f:
                content = content.replace(
                    replacer,
                    f.file.url)

        return content

    def add_url_references(self, content):
        """
        добавляем урлы ссылок для документации
        """
        refs = set([ref for title, ref in self.re_references.findall(content)])
        refs = {
            ref.socr: ref.url
            for ref in DocsReferenc.objects.filter(socr__in=refs)
        }

        for title, ref in set(self.re_references.findall(content)):
            if ref in refs:
                content = content.replace(
                    u'[{0}][{1}]'.format(title, ref),
                    u'[{0}]({1})'.format(title, refs[ref]))

        return content

    def add_code_style(self, content):
        """
        добавялем подсветку кода
        """
        code_start = u'<pre><code>'
        code_end = u'</code></pre>'
        code_start_len = len(code_start)

        is_code = False
        _lexer = 'text'
        code = []
        result = []

        for line in content.splitlines():
            if line.startswith(code_start):
                is_code = True
                _lexer = line[code_start_len:].strip()
            elif line.endswith(code_end):
                is_code = False
                try:
                    lexer = get_lexer_by_name(_lexer, stripall=True)
                except ValueError:
                    lexer = get_lexer_by_name('text', stripall=True)
                formatter = HtmlFormatter()
                result.append(
                    highlight(
                        u'\n'.join(
                            i.replace('&lt;', '<').replace('&gt;', '>')
                            for i in code),
                        lexer,
                        formatter))
                code = []
            elif is_code:
                code.append(line)
            else:
                result.append(line)

        return u'\n'.join(result)

    def set_tables_classes(self, content):
        """
        добавляет классы для таблиц
        :param content:
        :return:
        """
        root = html.parse(StringIO(content))
        table_wrappers = root.xpath('//div[@class="table_wrapper"]')
        for table_wrapper in table_wrappers:
            table = table_wrapper.getnext()
            if table:
                table.attrib['class'] = table_wrapper.attrib.get(
                    'data-table-class', "")
        return html.tostring(root)

    def tag_names(self):
        return ', '.join(
            pt.tag for pt in self.posttags_set.order_by('tag__name'))


class DocsReferenc(models.Model):

    category = models.ForeignKey(Category)
    socr = models.CharField(max_length=100, unique=True)
    url = models.URLField(unique=True)

    def __unicode__(self):
        return u'{0} / {1}'.format(self.socr, self.url)


class Comment(models.Model):

    user = models.ForeignKey(User, null=True, blank=True)
    user_name = models.CharField(
        u'Anonim username', max_length=50, null=True, blank=True)
    user_email = models.CharField(
        u'Anonim email', max_length=50, null=True, blank=True)

    content = models.TextField()
    content_raw = models.TextField()

    published = models.BooleanField(default=False)

    created = models.DateTimeField(u'Comment created date', auto_now_add=True)
    modified = models.DateTimeField(u'Comment modified date', auto_now=True)

    post = models.ForeignKey(Post)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return u'{0}'.format(
            self.user or u'{0} / {1}'.format(self.user_name, self.user_email))

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.content = markdown(self.content_raw)
        super(Comment, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)


class File(models.Model):
    file_name = models.CharField(max_length=100, blank=True)
    file = models.FileField()
    created = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.file

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.file_name = self.file.name
        super(File, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)

blog/views.py
# coding: utf-8

import datetime
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404
from django.http.response import HttpResponseForbidden
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from application.views import ConspectsMixin
from blog.models import Post, Category, Comment
from blog.tasks import send_email_notification


class BlogViewMixin(ConspectsMixin):

    def get_context_data(self, **kwargs):
        context = super(BlogViewMixin, self).get_context_data(**kwargs)
        context['active_page'] = 'blog'
        context['categories'] = Category.objects.all()
        return context


class PostListView(BlogViewMixin, ListView):
    model = Post
    paginate_by = 10
    current_category = None

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        context['current_category'] = self.current_category
        return context

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()

        current_category_name = self.kwargs.get("category_name", "")
        if current_category_name:
            try:
                self.current_category = Category.objects.get(
                    name=current_category_name)
            except Category.DoesNotExist:
                raise Http404()
            else:
                queryset = queryset.filter(category=self.current_category)

        if not self.request.user.is_superuser:
            queryset = queryset.filter(published=True)

        return queryset


class PostDetailView(BlogViewMixin, DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)

        object_comments = self.object.comment_set.all()

        if not self.request.user.is_superuser:
            object_comments = object_comments.filter(published=True)

        context['object_comments'] = object_comments
        return context

    def get_object(self, queryset=None):
        object = super(PostDetailView, self).get_object(queryset=queryset)
        if (object and
                not object.published and
                not self.request.user.is_superuser):
            raise PermissionDenied()
        return object


class PostCreateView(BlogViewMixin, CreateView):
    model = Post
    fields = [
        "title",
        "raw_content",
        "category",
        "published",
        "description",
    ]

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostCreateView, self).post(request, *args, **kwargs)


class PostUpdateView(BlogViewMixin, UpdateView):
    model = Post
    fields = [
        "title",
        "raw_content",
        "category",
        "published",
        "description",
    ]

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostUpdateView, self).post(request, *args, **kwargs)


class PostDeleteView(BlogViewMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:list", args=[""])

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostDeleteView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return super(PostDeleteView, self).post(request, *args, **kwargs)


def comment_create(request, post_slug):

    try:
        post = Post.objects.get(slug=post_slug)
    except Post.DoesNotExist:
        raise Http404()

    if "content_raw" not in request.POST:
        return redirect(
            reverse("blog:post_detail", args=[post.category.name, post_slug]))

    if not post.published and not request.user.is_superuser:
        raise PermissionDenied()

    comment = Comment()
    if request.user.is_authenticated():
        comment.user = request.user
    else:
        if ('user_name' not in request.POST or
                'user_email' not in request.POST):
            return redirect(
                reverse(
                    "blog:post_detail", args=[post.category.name, post_slug]))

        comment.user_name = request.POST['user_name']
        comment.user_email = request.POST['user_email']

    comment.content_raw = request.POST['content_raw']
    comment.post = post
    comment.save()

    send_email_notification.delay(
        title=u'Новый коментарии',
        message=u'Новый коменатрии \n{0}\n{1}'.format(
            reverse('blog:post_detail', args=[post.category.name, post_slug]),
            datetime.datetime.now()))

    return redirect(
        reverse("blog:post_detail", args=[post.category.name, post_slug]))

blog/templates/blog/base.html
{% extends 'base.html' %}

{% block extra_head %}
    {% block extra_blog_head %}{% endblock %}
{% endblock %}

{% block extra_body %}
    <div class="container">
        <ul class="nav nav-pills">
            {% for category in categories %}
                <li
                        role="presentation"
                        {% if current_category == category %}
                            class="active"
                        {% endif %}>
                    <a href="{% url "blog:list" category.name %}">
                        <h4>{{ category.name|upper }}</h4>
                    </a>
                </li>
            {% endfor %}
        </ul>
        <br>
        {% if view.request.user.is_superuser %}
            <a class="btn btn-primary " href="{% url 'blog:post_create' %}" role="button">
                Добавить
            </a>
            <br>
            <br>
        {% endif %}
    </div>
    {% block extra_blog_body %}{% endblock %}
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block extra_blog_head %}
{% endblock %}

{% block title %}
    Удаление сообщения
{% endblock %}

{% block extra_blog_body %}
    <div class="container">
        <form action="" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-danger">
                        Удалить пост -> {{ object }}
                    </button>
                </div>
            </div>
        </form>

    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block extra_blog_head %}
{% endblock %}

{% block title %}
    {{ object.category }}: {{ object }}
{% endblock %}

{% block description %}
    <meta name="description" content="{{ object.description }}">
{% endblock %}

{% block extra_blog_body %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{ object.title }}</h3>
            </div>
            <div class="panel-body ">
                {{ object.content|safe }}
            </div>
            <div class="panel-footer text-right">
                <a href="{% url 'blog:list' object.category.slug %}">
                    {{ object.category }}
                </a>/{{ object.created }} ({{ object.modified }})
                {% if view.request.user.is_superuser %}
                    {% if object.published %}
                        <span class="label label-success">Опубликован</span>
                    {% else %}
                        <span class="label label-warning">Скрыт</span>
                    {% endif %}
                    <a type="button"
                       class="btn btn-info"
                       href="{% url 'blog:post_update' object.slug %}">
                        Редактировать
                    </a>
                    <a type="button"
                       class="btn btn-danger"
                       href="{% url 'blog:post_delete' object.slug %}">
                        Удалить
                    </a>
                {% endif %}
            </div>
        </div>
        <form class="form-horizontal"
              method="post"
              enctype="multipart/form-data"
              action="{% url 'blog:comment_create' post.slug %}">
            {% csrf_token %}
            {% if not view.request.user.is_authenticated %}
                <div class="form-group">
                    <label for="user_name" class="col-sm-2 control-label">
                        Ваше имя
                    </label>
                    <div class="col-sm-10">
                        <input
                                type="text"
                                class="form-control"
                                id="user_name"
                                placeholder="имя"
                                name="user_name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="user_email" class="col-sm-2 control-label">
                        Ваш email
                    </label>
                    <div class="col-sm-10">
                        <input
                                type="text"
                                class="form-control"
                                id="user_email"
                                placeholder="email"
                                name="user_email">
                    </div>
                </div>
            {% endif %}
            <div class="form-group">
                <label for="content_raw" class="col-sm-2 control-label">
                    Коментарии (markdown)
                </label>
                <div class="col-sm-10">
                    <textarea
                            class="form-control"
                            id="content_raw"
                            name="content_raw"
                            rows="5"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">
                        Добавить коментарии
                    </button>
                </div>
            </div>
        </form>

        {% for comment in object_comments %}
            <div class="row">
                <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 text-right">
                    <h3><span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span></h3>
                </div>
                <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                    <h3>
                        {% if comment.user %}
                            {{ comment.user }}
                        {% else %}
                            {{ comment.user_name }}
                        {% endif %}
                        <small>({{ comment.created }})</small>
                        {% if view.request.user.is_superuser %}
                            {% if comment.published %}
                                <span class="label label-success">Опубликован</span>
                            {% else %}
                                <span class="label label-warning">Скрыт</span>
                            {% endif %}
                            <a type="button"
                               class="btn btn-info"
                               href="/admin/blog/comment/{{ comment.id }}">
                                Редактировать
                            </a>
                            <a type="button"
                               class="btn btn-danger"
                               href="/admin/blog/comment/{{ comment.id }}/delete">
                                Удалить
                            </a>
                        {% endif %}
                    </h3>
                    {{ comment.content|safe }}
                    <hr>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block extra_blog_head %}
{% endblock %}

{% block title %}
    {% if current_category %}
        {{ current_category }}.
    {% endif %}
    Блог.
{% endblock %}

{% block description %}
    {% if current_category %}
        <meta name="description" content="Посты блога Ильнура Гайфутдинова по теме {{ current_category }}">
    {% else %}
        <meta name="description" content="Посты блога Ильнура Гайфутдинова">
    {% endif %}
{% endblock %}

{% block extra_blog_body %}
    <div class="container">
        {% for post in object_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><a href="{% url "blog:post_detail" post.category.name post.slug %}">{{ post.title }}</a></h3>
                </div>
                <div class="panel-body ">
                    {{ post.content|safe|truncatewords_html:50 }}
                </div>
                <div class="panel-footer text-right">
                    <a href="{% url "blog:list" post.category %}">
                        {{ post.category }}
                    </a>/
                    {{ post.created }} ({{ post.modified }})
                    {% if view.request.user.is_superuser %}
                        {% if post.published %}
                            <span class="label label-success">Опубликован</span>
                        {% else %}
                            <span class="label label-warning">Скрыт</span>
                        {% endif %}
                        <a type="button"
                           class="btn btn-info"
                           href="{% url 'blog:post_update' post.slug %}">
                            Редактировать
                        </a>
                        <a type="button"
                           class="btn btn-danger"
                           href="{% url 'blog:post_delete' post.slug %}">
                            Удалить
                        </a>
                    {% endif %}

                </div>
            </div>
        {% endfor %}

        <nav>
            <ul class="pager">
                <li class="previous {% if not page_obj.has_previous %}disabled{% endif %}">
                    <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">
                        <span aria-hidden="true">&larr;</span>
                        Новые
                    </a>
                </li>
                <li class="next {% if not page_obj.has_next %}disabled{% endif %}">
                    <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
                        Старые
                        <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}