application/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.sitemaps.views import sitemap
from django.http.response import HttpResponse

from application import views as app_view
from application.constants import CONSPECTS
from application.sitemap import ApplicationSitemap, ConspectsSitemap

from blog import urls as blog_urls
from blog.sitemaps import BlogSitemap
from cars import urls as cars_urls
from fileuploader import urls as fileuploader_urls
from metrics import urls as metric_urls
from resume import urls as resume_urls


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {
            "sitemaps": {
                "main": ApplicationSitemap,
                "blog": BlogSitemap,
                "conspects": ConspectsSitemap,
            }
        },
        "sitemap_xml"),
    url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-Agent: *\nDisallow: \nHost: ilnurgi1.ru\n",
            content_type="text/plain")),
    url(
        r'^admin/',
        include(admin.site.urls)),
    url(
        r'^blog/',
        include(blog_urls, namespace='blog')),
    url(
        r'^fileuploader/',
        include(fileuploader_urls, namespace='fileuploader')),
    url(
        r'^sitemap/',
        app_view.SiteMap.as_view(), name='sitemap'),
    url(
        r'^metrics/',
        include(metric_urls, namespace='metrics')),
    url(
        r'^conspects/$',
        app_view.ConspectsPage.as_view(),
        name='conspects_page'),
    url(
        r'^cars/',
        include(cars_urls, namespace='cars')),
    url(
        r'^login/',
        login,
        {
            "template_name": "application/login.html",
            "extra_context": {
                "conspects": CONSPECTS,
            }
        },
        'login'),
    url(
        r'^logout/',
        logout,
        {
            "next_page": "resume:home_page"
        },
        'logout'),
    url(
        r'^$',
        include(resume_urls, namespace="resume")),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blog/urls.py
# coding: utf-8

from django.conf.urls import url

from blog import views

urlpatterns = [

    url(
        r'comment_create/(?P<post_slug>.+)',
        views.comment_create,
        name='comment_create'),
    url(
        r'post/create',
        views.PostCreateView.as_view(),
        name='post_create'),
    url(
        r'post/edit/(?P<slug>.+)',
        views.PostUpdateView.as_view(),
        name='post_update'),
    url(
        r'post/delete/(?P<slug>.+)',
        views.PostDeleteView.as_view(),
        name='post_delete'),
    url(
        r'(?P<category_name>\w*)/(?P<slug>.+)',
        views.PostDetailView.as_view(),
        name='post_detail'),
    url(
        r'(?P<category_name>\w*)$',
        views.PostListView.as_view(),
        name='list'),
]

ilnurgi/ilnurgi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ilnurgi import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', include(admin.site.urls))
]

blog/models.py
# coding: utf-8

import re

from io import StringIO
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

from markdown import markdown

from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter

from pytils.translit import slugify

import lxml.html as html


class Category(models.Model):

    name = models.CharField(u'Name', max_length=50, unique=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Post(models.Model):

    title = models.CharField(u'Post title', max_length=100)
    raw_content = models.TextField(u'Post raw content')
    content = models.TextField(u'Post content')
    published = models.BooleanField(default=False)
    category = models.ForeignKey(Category)

    created = models.DateTimeField(u'Post created date', auto_now_add=True)
    modified = models.DateTimeField(u'Post modified date', auto_now=True)

    slug = models.SlugField(blank=True, unique=True)

    description = models.CharField(u'Description', max_length=255)

    re_references = re.compile(u'\[(.+?)\]\[(.+?)\]')
    re_files = re.compile(u'(\[FILE=(\d+)\])')

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.category.name, self.slug])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.content = (
            self.set_tables_classes(
                self.add_files(
                    self.add_code_style(
                        markdown(
                            self.add_url_references(
                                self.raw_content),
                            extensions=['tables']
                        )))))
        self.slug = slugify(self.title)

        super(Post, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)

    def add_files(self, content):
        finds = self.re_files.findall(content)
        file_ids = [int(file_id) for _, file_id in finds]
        file_ids_map = {
            f.id: f for f in File.objects.filter(id__in=file_ids)
        }
        for replacer, file_id in finds:
            f = file_ids_map.get(int(file_id))
            if f:
                content = content.replace(
                    replacer,
                    f.file.url)

        return content

    def add_url_references(self, content):
        """
        добавляем урлы ссылок для документации
        """
        refs = set([ref for title, ref in self.re_references.findall(content)])
        refs = {
            ref.socr: ref.url
            for ref in DocsReferenc.objects.filter(socr__in=refs)
        }

        for title, ref in set(self.re_references.findall(content)):
            if ref in refs:
                content = content.replace(
                    u'[{0}][{1}]'.format(title, ref),
                    u'[{0}]({1})'.format(title, refs[ref]))

        return content

    def add_code_style(self, content):
        """
        добавялем подсветку кода
        """
        code_start = u'<pre><code>'
        code_end = u'</code></pre>'
        code_start_len = len(code_start)

        is_code = False
        _lexer = 'text'
        code = []
        result = []

        for line in content.splitlines():
            if line.startswith(code_start):
                is_code = True
                _lexer = line[code_start_len:].strip()
            elif line.endswith(code_end):
                is_code = False
                try:
                    lexer = get_lexer_by_name(_lexer, stripall=True)
                except ValueError:
                    lexer = get_lexer_by_name('text', stripall=True)
                formatter = HtmlFormatter()
                result.append(
                    highlight(
                        u'\n'.join(
                            i.replace('&lt;', '<').replace('&gt;', '>')
                            for i in code),
                        lexer,
                        formatter))
                code = []
            elif is_code:
                code.append(line)
            else:
                result.append(line)

        return u'\n'.join(result)

    def set_tables_classes(self, content):
        """
        добавляет классы для таблиц
        :param content:
        :return:
        """
        root = html.parse(StringIO(content))
        table_wrappers = root.xpath('//div[@class="table_wrapper"]')
        for table_wrapper in table_wrappers:
            table = table_wrapper.getnext()
            if table:
                table.attrib['class'] = table_wrapper.attrib.get(
                    'data-table-class', "")
        return html.tostring(root)

    def tag_names(self):
        return ', '.join(
            pt.tag for pt in self.posttags_set.order_by('tag__name'))


class DocsReferenc(models.Model):

    category = models.ForeignKey(Category)
    socr = models.CharField(max_length=100, unique=True)
    url = models.URLField(unique=True)

    def __unicode__(self):
        return u'{0} / {1}'.format(self.socr, self.url)


class Comment(models.Model):

    user = models.ForeignKey(User, null=True, blank=True)
    user_name = models.CharField(
        u'Anonim username', max_length=50, null=True, blank=True)
    user_email = models.CharField(
        u'Anonim email', max_length=50, null=True, blank=True)

    content = models.TextField()
    content_raw = models.TextField()

    published = models.BooleanField(default=False)

    created = models.DateTimeField(u'Comment created date', auto_now_add=True)
    modified = models.DateTimeField(u'Comment modified date', auto_now=True)

    post = models.ForeignKey(Post)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return u'{0}'.format(
            self.user or u'{0} / {1}'.format(self.user_name, self.user_email))

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.content = markdown(self.content_raw)
        super(Comment, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)


class File(models.Model):
    file_name = models.CharField(max_length=100, blank=True)
    file = models.FileField()
    created = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.file

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.file_name = self.file.name
        super(File, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)

application/views.py
# coding: utf-8

from django.views.generic import TemplateView

from application.constants import CONSPECTS
from blog.models import Category


class ConspectsMixin(object):

    def get_context_data(self, **kwargs):
        context = super(ConspectsMixin, self).get_context_data(**kwargs)
        context['conspects'] = CONSPECTS
        return context


class SiteMap(ConspectsMixin, TemplateView):
    template_name = 'application/sitemap.html'

    def get_context_data(self, **kwargs):
        context = super(SiteMap, self).get_context_data(**kwargs)

        context['active_page'] = 'sitemap'

        categories = Category.objects
        if not self.request.user.is_superuser:
            categories = categories.filter(post__published=True)
        context['categories'] = categories.all()
        return context


class ConspectsPage(ConspectsMixin, TemplateView):
    template_name = 'application/conspects.html'

application/templates/application/conspects.html
{% extends 'base.html' %}

{% block title %}
    Конспекты
{% endblock %}

{% block description %}
    <meta name="description" content="Конспекты Ильнура Гайфутдинова по различным технологиям">
{% endblock %}

{% block extra_body %}
    <div class="container">
        <div class="container">
            <div class="row">
                {% for conspect_items in conspects %}
                    <div class="col-xs-12 col-sm-4 col-md-3">
                        <div class="list-group">
                            {% for conspect in conspect_items %}
                                <a
                                        href="{{ conspect.url }}"
                                        class="list-group-item"
                                >
                                    {{ conspect.title }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

application/templates/application/login.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block description %}
    <meta name="description" content="Страница авторизации на сайте">
{% endblock %}

{% block extra_body %}

    <div class="container">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" placeholder="username" name="username">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" placeholder="Password" name="password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Войти</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

application/templates/application/sitemap.html
{% extends 'base.html' %}

{% block title %}
    Карта сайта
{% endblock %}

{% block description %}
    <meta name="description" content="Карта сайта">
{% endblock %}

{% block extra_body %}
    <div class="container">
        <ul>
        {% for category in categories %}
            <li>
                <a href="{% url 'blog:list' category.name %}">{{ category }}</a>
                <ul>
                    {% for post in category.post_set.all %}
                        <li>
                            <a href="{% url 'blog:post_detail' post.category.name post.slug %}">{{ post }}</a>
                            {% if view.request.user.is_superuser %}
                                {% if post.published %}
                                    <span class="label label-success">Опубликован</span>
                                {% else %}
                                    <span class="label label-warning">Скрыт</span>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ul>

        <div class="row">
            {% for conspect_items in conspects %}
                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="list-group">
                        {% for conspect in conspect_items %}
                            <a
                                    href="{{ conspect.url }}"
                                    class="list-group-item"
                            >
                                {{ conspect.title }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}