application/urls.py
# coding: utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.sitemaps.views import sitemap
from django.http.response import HttpResponse

from application import views as app_view
from application.constants import CONSPECTS
from application.sitemap import ApplicationSitemap, ConspectsSitemap

from blog import urls as blog_urls
from blog.sitemaps import BlogSitemap
from cars import urls as cars_urls
from fileuploader import urls as fileuploader_urls
from metrics import urls as metric_urls
from resume import urls as resume_urls


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {
            "sitemaps": {
                "main": ApplicationSitemap,
                "blog": BlogSitemap,
                "conspects": ConspectsSitemap,
            }
        },
        "sitemap_xml"),
    url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-Agent: *\nDisallow: \nHost: ilnurgi1.ru\n",
            content_type="text/plain")),
    url(
        r'^admin/',
        include(admin.site.urls)),
    url(
        r'^blog/',
        include(blog_urls, namespace='blog')),
    url(
        r'^fileuploader/',
        include(fileuploader_urls, namespace='fileuploader')),
    url(
        r'^sitemap/',
        app_view.SiteMap.as_view(), name='sitemap'),
    url(
        r'^metrics/',
        include(metric_urls, namespace='metrics')),
    url(
        r'^conspects/$',
        app_view.ConspectsPage.as_view(),
        name='conspects_page'),
    url(
        r'^cars/',
        include(cars_urls, namespace='cars')),
    url(
        r'^login/',
        login,
        {
            "template_name": "application/login.html",
            "extra_context": {
                "conspects": CONSPECTS,
            }
        },
        'login'),
    url(
        r'^logout/',
        logout,
        {
            "next_page": "resume:home_page"
        },
        'logout'),
    url(
        r'^$',
        include(resume_urls, namespace="resume")),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blog/urls.py
# coding: utf-8

from django.conf.urls import url

from blog import views

urlpatterns = [

    url(
        r'comment_create/(?P<post_slug>.+)',
        views.comment_create,
        name='comment_create'),
    url(
        r'post/create',
        views.PostCreateView.as_view(),
        name='post_create'),
    url(
        r'post/edit/(?P<slug>.+)',
        views.PostUpdateView.as_view(),
        name='post_update'),
    url(
        r'post/delete/(?P<slug>.+)',
        views.PostDeleteView.as_view(),
        name='post_delete'),
    url(
        r'(?P<category_name>\w*)/(?P<slug>.+)',
        views.PostDetailView.as_view(),
        name='post_detail'),
    url(
        r'(?P<category_name>\w*)$',
        views.PostListView.as_view(),
        name='list'),
]

ilnurgi/ilnurgi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ilnurgi import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', include(admin.site.urls))
]

metrics/urls.py
# coding: utf-8

from django.conf.urls import url

from metrics import views

urlpatterns = [
    url(
        r'cpu_data',
        views.cpu_data,
        name='cpu_data'),
    url(
        r'cpu_hour_data',
        views.cpu_hour_data,
        name='cpu_hour_data'),
    url(
        r'mem_data',
        views.mem_data,
        name='mem_data'),
    url(
        r'mem_hour_data',
        views.mem_hour_data,
        name='mem_hour_data'),
    url(
        r'system',
        views.System.as_view(),
        name='system'),

    url(
        r'data_week',
        views.data_week,
        name='data_week'),

    url(
        r'data_month',
        views.data_month,
        name='data_month'),
    url(
        r'docs_data_all',
        views.docs_data_all,
        name='docs_data_all'),

    url(
        r'visiters',
        views.Visiters.as_view(),
        name='visiters'),

    url(
        r'urls_from',
        views.URLSFrom.as_view(),
        name='urls_from'),

    url(
        r'urls',
        views.URLS.as_view(),
        name='urls'),

    url(
        r'user_agents',
        views.UserAgents.as_view(),
        name='user_agents'),

    url(
        r'',
        views.HomePage.as_view(),
        name='home_page'),
]

metrics/views.py
# coding: utf-8

import datetime
import json

import pymongo

from django.conf import settings
from django.http import JsonResponse
from django.views.generic import TemplateView

from application.views import ConspectsMixin


class HomePage(ConspectsMixin, TemplateView):

    template_name = 'base_metrics.html'
    active_page_sub = ''

    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        context['active_page'] = 'metrics'
        context['active_page_sub'] = self.active_page_sub
        return context


class System(HomePage):

    template_name = 'metrics_system.html'
    active_page_sub = "system"


class Visiters(HomePage):

    template_name = 'metrics_visiters.html'
    active_page_sub = "visiters"


class URLS(HomePage):

    template_name = 'metrics_urls.html'
    active_page_sub = "urls"

    def get_context_data(self, **kwargs):
        context = super(URLS, self).get_context_data(**kwargs)

        mongo_client = pymongo.MongoClient(
            settings.DATABASE_MONGO['host'],
            int(settings.DATABASE_MONGO['port']))

        db = mongo_client[settings.DATABASE_MONGO['nginx_access_db_name']]

        docs = db.month_report.find().sort('date', -1)
        context['urls'] = []

        for doc in docs:
            urls = json.loads(doc['urls']).items()
            urls.sort(key=lambda x: x[1], reverse=True)
            context['urls'].append({
                'date': doc['date'],
                'urls': urls
            })

        return context


class URLSFrom(HomePage):

    template_name = 'metrics_urls.html'
    active_page_sub = "urls_from"

    def get_context_data(self, **kwargs):
        context = super(URLSFrom, self).get_context_data(**kwargs)

        mongo_client = pymongo.MongoClient(
            settings.DATABASE_MONGO['host'],
            int(settings.DATABASE_MONGO['port']))

        db = mongo_client[settings.DATABASE_MONGO['nginx_access_db_name']]

        docs = db.month_report.find().sort('date', -1)
        context['urls'] = []

        for doc in docs:
            urls = json.loads(doc['urls_from']).items()
            urls.sort(key=lambda x: x[1], reverse=True)
            context['urls'].append({
                'date': doc['date'],
                'urls': urls
            })

        return context


class UserAgents(HomePage):

    template_name = 'metrics_urls.html'
    active_page_sub = "user_agents"

    def get_context_data(self, **kwargs):
        context = super(UserAgents, self).get_context_data(**kwargs)

        mongo_client = pymongo.MongoClient(
            settings.DATABASE_MONGO['host'],
            int(settings.DATABASE_MONGO['port']))

        db = mongo_client[settings.DATABASE_MONGO['nginx_access_db_name']]

        docs = db.month_report.find().sort('date', -1)
        context['urls'] = []

        for doc in docs:
            urls = json.loads(doc['user_agents']).items()
            urls.sort(key=lambda x: x[1], reverse=True)
            context['urls'].append({
                'date': doc['date'],
                'urls': urls
            })

        return context


def get_db(db_name):
    """
    возвращаем БД

    :param db_name:
    :return:
    """
    mongo_client = pymongo.MongoClient(
        settings.DATABASE_MONGO['host'],
        int(settings.DATABASE_MONGO['port']))

    return mongo_client[db_name]


def cpu_data(request):

    db = get_db(settings.DATABASE_MONGO['cpu_average_db_name'])

    cpu_times = []
    cpu_times_append = cpu_times.append

    cpu_average = []
    cpu_average_append = cpu_average.append

    for i in db.average_minute.find({
        'date': {
            '$gte': datetime.datetime.now() - datetime.timedelta(minutes=30)
        }
    }).sort('date'):
        cpu_times_append(i['date'].strftime('%H:%M'))
        cpu_average_append(i['percent'])
    return JsonResponse({
        'labels': cpu_times,
        'data': cpu_average
    })


def cpu_hour_data(request):
    db = get_db(settings.DATABASE_MONGO['cpu_average_db_name'])

    cpu_times = []
    cpu_times_append = cpu_times.append

    cpu_average = []
    cpu_average_append = cpu_average.append

    for i in db.average_hour.find().sort('date'):
        cpu_times_append(i['date'].strftime('%d.%m.%Y (%H)'))
        cpu_average_append(i['percent'])
    return JsonResponse({
        'labels': cpu_times,
        'data': cpu_average
    })


def mem_data(request):
    db = get_db(settings.DATABASE_MONGO['mem_average_db_name'])

    cpu_times = []
    cpu_times_append = cpu_times.append

    cpu_average = []
    cpu_average_append = cpu_average.append

    for i in db.average_minute.find({
        'date': {
            '$gte': datetime.datetime.now() - datetime.timedelta(minutes=30)
        }
    }).sort('date'):
        cpu_times_append(i['date'].strftime('%H:%M'))
        cpu_average_append(i['percent'])
    return JsonResponse({
        'labels': cpu_times,
        'data': cpu_average
    })


def mem_hour_data(request):
    db = get_db(settings.DATABASE_MONGO['mem_average_db_name'])

    cpu_times = []
    cpu_times_append = cpu_times.append

    cpu_average = []
    cpu_average_append = cpu_average.append

    for i in db.average_hour.find().sort('date'):
        cpu_times_append(i['date'].strftime('%d.%m.%Y (%H)'))
        cpu_average_append(i['percent'])
    return JsonResponse({
        'labels': cpu_times,
        'data': cpu_average
    })


def get_records(collection, date_start, date_end):
    """
    итератор, возвращает данные из коллекции, делая запрос по дням

    :param collection:

    :param date_start: начало среза
    :type date_start: datetime.datetime

    :param date_end: конец среза
    :type date_end: datetime.datetime

    :return:
    """
    delta = date_end - date_start
    for i in xrange(delta.days + 1):
        _date_start = date_start + datetime.timedelta(days=i)
        _date_end = date_start + datetime.timedelta(days=i + 1)
        for record in collection.find(
                {
                    'date': {
                        '$gte': _date_start,
                        '$lt': _date_end
                    }
                }).sort('date'):
            yield record
        if _date_end == date_end:
            break


def data_month(requset):
    """
    информация по посещаемости по месяцам
    возвращает жсон,
    {
        'labels': список дат
        'ip_count': список количеств ипи по дням
        'ip_count_uniq': список количеств уникальных ипи по дням
        'doc_all_count': список количеств просмотров конспектов по дням
        'blog_all_count': список количеств просмотров блога по дням
    }

    :param requset:
    :return:
    """
    db = get_db(settings.DATABASE_MONGO['nginx_access_db_name'])

    times = []
    times_append = times.append

    _ip_data = []
    ip_data_append = _ip_data.append

    _ip_uniq_data = []
    ip_uniq_data_append = _ip_uniq_data.append

    _docs_data = []
    docs_data_append = _docs_data.append

    _blog_data = []
    blog_data_append = _blog_data.append

    for i in db.month_report.find().sort('date'):
        times_append(i['date'].strftime('%d.%m.%Y'))
        ip_data_append(i['ip_count'])
        ip_uniq_data_append(i['ip_uniq_count'])

        docs_counter = 0
        blog_counter = 0
        for url, count in json.loads(i['urls']).iteritems():
            if url.startswith('/docs/'):
                docs_counter += count
            elif url.startswith('/blog/'):
                blog_counter += count
        docs_data_append(docs_counter)
        blog_data_append(blog_counter)

    return JsonResponse({
        'labels': times,
        'ip_count': _ip_data,
        'ip_count_uniq': _ip_uniq_data,
        'doc_all_count': _docs_data,
        'blog_all_count': _blog_data,
    })


def data_week(request):
    """
    информация по посещаемости за последнюю неделю
    возвращает жсон,
    {
        'labels': список дат
        'ip_count': список количеств ипи по дням
        'ip_count_uniq': список количеств уникальных ипи по дням
        'doc_all_count': список количеств просмотров конспектов по дням
        'blog_all_count': список количеств просмотров блога по дням
    }
    """
    db = get_db(settings.DATABASE_MONGO['nginx_access_db_name'])

    times = []
    times_append = times.append

    _ip_data = []
    ip_data_append = _ip_data.append

    _ip_uniq_data = []
    ip_uniq_data_append = _ip_uniq_data.append

    _docs_all_data = []
    docs_all_data_append = _docs_all_data.append

    _blog_all_data = []
    blog_all_data_append = _blog_all_data.append

    if "date_now" in request.GET:
        date_now = datetime.datetime.strptime(
            request.GET["date_now"],
            "%Y.%m.%d %H.%M.%S")
    else:
        date_now = datetime.datetime.now()

    # date_now = datetime.datetime.now() - datetime.timedelta(days=15)
    date_end = datetime.datetime.combine(
        date_now.date() - datetime.timedelta(days=1),
        datetime.time(23, 59, 59)
    )
    date_start = datetime.datetime.combine(
        (date_end - datetime.timedelta(weeks=1)).date(),
        datetime.time(0, 0, 0)
    )

    last_date = None
    ip_count = 0
    ip_uniq_count_set = set()
    docs_all_count = 0
    blog_all_count = 0

    for record in get_records(db.log, date_start=date_start, date_end=date_end):

        record_date = record['date'].date()

        if not last_date:
            last_date = record_date

        if last_date != record_date:
            times_append(last_date.strftime('%d.%m.%Y'))
            ip_data_append(ip_count)
            ip_uniq_data_append(len(ip_uniq_count_set))
            docs_all_data_append(docs_all_count)
            blog_all_data_append(blog_all_count)

            last_date = record_date
            ip_count = 0
            ip_uniq_count_set.clear()
            docs_all_count = 0
            blog_all_count = 0

        if not any(excl_ua in record['user_agent']

metrics/templates/base_metrics.html
{% extends 'base.html' %}

{% block extra_head %}
    <script src="{{ STATIC_URL }}Chart.min.js"></script>
    {% block extra_metrics_head %}{% endblock %}
{% endblock %}

{% block title %}
    Статистика. {% block extra_title %}{% endblock %}
{% endblock %}

{% block description %}
    <meta name="description" content="Статистика ресурса">
{% endblock %}

{% block extra_body %}
    <div class="container">
        <ul class="nav nav-pills">
            <li
                    role="presentation"
                    {% if active_page_sub == 'system' %}
                        class="active"
                    {% endif %}>
                <a href="{% url 'metrics:system' %}">Система</a>
            </li>
            <li
                    role="presentation"
                    {% if active_page_sub == 'visiters' %}
                        class="active"
                    {% endif %}>
                <a href="{% url 'metrics:visiters' %}">Посещаемость</a>
            </li>
            {% if view.request.user.is_superuser %}
                <li
                        role="presentation"
                        {% if active_page_sub == 'urls' %}
                            class="active"
                        {% endif %}>
                    <a href="{% url 'metrics:urls' %}">urls</a>
                </li>
                <li
                        role="presentation"
                        {% if active_page_sub == 'urls_from' %}
                            class="active"
                        {% endif %}>
                    <a href="{% url 'metrics:urls_from' %}">urls_from</a>
                </li>
                <li
                        role="presentation"
                        {% if active_page_sub == 'user_agents' %}
                            class="active"
                        {% endif %}>
                    <a href="{% url 'metrics:user_agents' %}">user_agents</a>
                </li>
            {% endif %}
        </ul>
        <br>
        {% block content %}
            На данной странице собрал различную статистику по моему сайту.
            <br>Данные я отображаю в виде различных диграмм и т.п. с использованием JS библиотек
        {% endblock %}
    </div>
{% endblock %}

metrics/templates/metrics_system.html
{% extends 'base_metrics.html' %}

{% block extra_title %}
    Система.
{% endblock %}

{% block description %}
    <meta name="description" content="Статистика ресурса. Система.">
{% endblock %}

{% block extra_metrics_head %}
    <script>
        function createChartJs(json, label, canvas_id, legend_id){
            var data = {
                labels : json.labels,
                datasets : [
                    {
                        label: label,
                        data : json.data,
                        fillColor: "rgba(220,220,220,0.2)",
                        strokeColor: "rgba(220,220,220,1)",
                        pointColor: "rgba(220,220,220,1)",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(220,220,220,1)"
                    }
                ]
            };

            var ctx = document.getElementById(canvas_id).getContext("2d");
            var line = new Chart(ctx).Line(data);
            var div_legend = document.getElementById(legend_id);
            div_legend.innerHTML = line.generateLegend();
        }

        function createCPUCharts(json){
            createChartJs(
                json,
                'Chart.js, cpu load',
                "canvas_cpu_chartjs",
                "div_legend_cpu_chartjs");
        }

        function createCPUHourCharts(json){
            createChartJs(
                json,
                'Chart.js, cpu load hour',
                "canvas_cpu_hour_chartjs",
                "div_legend_cpu_hour_chartjs");
        }

        function createMEMCharts(json){
            createChartJs(
                json,
                'Chart.js, mem load',
                "canvas_mem_chartjs",
                "div_legend_mem_chartjs");
        }

        function createMEMHourCharts(json){
            createChartJs(
                json,
                'Chart.js, mem load hour',
                "canvas_mem_hour_chartjs",
                "div_legend_mem_hour_chartjs");
        }

        function createCharts(){
            $.getJSON("{% url 'metrics:cpu_data' %}", createCPUCharts);
            $.getJSON("{% url 'metrics:cpu_hour_data' %}", createCPUHourCharts);
            $.getJSON("{% url 'metrics:mem_data' %}", createMEMCharts);
            $.getJSON("{% url 'metrics:mem_hour_data' %}", createMEMHourCharts);
        }
        $(document).ready(function(){
            Chart.defaults.global.tooltipEvents = [];
            Chart.defaults.global.responsive = true;
            Chart.defaults.global.animation = false;
            createCharts();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        {# chartjs row #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div id="div_legend_cpu_chartjs"></div>
            <canvas id="canvas_cpu_chartjs"></canvas>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div id="div_legend_mem_chartjs"></div>
            <canvas id="canvas_mem_chartjs"></canvas>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="div_legend_cpu_hour_chartjs"></div>
            <canvas id="canvas_cpu_hour_chartjs"></canvas>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="div_legend_mem_hour_chartjs"></div>
            <canvas id="canvas_mem_hour_chartjs"></canvas>
        </div>
    </div>
{% endblock %}

metrics/templates/metrics_urls.html
{% extends 'base_metrics.html' %}

{% block extra_title %}
    Урлы
{% endblock %}

{% block description %}
    <meta name="description" content="Статистика ресурса. Урлы">
{% endblock %}

{% block content %}
    {% for data in urls %}
        <h3>{{ data.date }}</h3>
        {% for url in data.urls %}
            <br>{{ url.1 }}, {{ url.0 }}
        {% endfor %}
    {% endfor %}
{% endblock %}

metrics/templates/metrics_visiters.html
{% extends 'base_metrics.html' %}

{% block extra_title %}
    Посещаемость
{% endblock %}

{% block description %}
    <meta name="description" content="Статистика ресурса. Посетители.">
{% endblock %}

{% block extra_metrics_head %}
    <script>
        function createChartJs(json, canvas_id){
            var data = {
                labels : json.labels,
                datasets : [
                    {
                        label: '',
                        data : json.data,
                        fillColor: "rgba(220,220,220,0.2)",
                        strokeColor: "rgba(220,220,220,1)",
                        pointColor: "rgba(220,220,220,1)",
                        pointStrokeColor: "#fff",
                        pointHighlightFill: "#fff",
                        pointHighlightStroke: "rgba(220,220,220,1)"
                    }
                ]
            };

            var ctx = document.getElementById(canvas_id).getContext("2d"),
                line = new Chart(ctx).Line(data);
        }

        /*
         * заполням чарты данными за неделю
         */
        function createDataWeekCharts(json){

            /*
             * заполняем ипи
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.ip_count
                },
                "canvas_ip_week_chartjs");

            /*
             * заполняем уникальные ипи
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.ip_count_uniq
                },
                "canvas_ip_uniq_week_chartjs");

            /*
             * заполняем просмотр документашки
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.doc_all_count
                },
                "canvas_docs_week_chartjs");

            /*
             * заполняем просмотр блога
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.blog_all_count
                },
                "canvas_blog_week_chartjs");
        }

        /*
         * заполням чарты данными за месяц
         */
        function createDataMonthCharts(json){

            /*
             * заполняем ипи
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.ip_count
                },
                "canvas_ip_chartjs");

            /*
             * заполняем уникальные ипи
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.ip_count_uniq
                },
                "canvas_ip_uniq_chartjs");

            /*
             * заполняем просмотр документашки
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.doc_all_count
                },
                "canvas_docs_chartjs");

            /*
             * заполняем просмотр блога
             */
            createChartJs(
                {
                    labels: json.labels,
                    data: json.blog_all_count
                },
                "canvas_blog_chartjs");
        }

        function createDocsAllCharts(json){
            var data = {
                labels : json.labels,
                datasets : [
                    {
                        label: "Android",
                        data : json.data_android,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#f00",
                        pointColor: "#f00",
                        pointStrokeColor: "#f00"
                    }, {
                        label: "Java",
                        data : json.data_java,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#b22222",
                        pointColor: "#b22222",
                        pointStrokeColor: "#b22222"
                    }, {
                        label: "DroidScript",
                        data : json.data_droidscript,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#8b0000",
                        pointColor: "#8b0000",
                        pointStrokeColor: "#8b0000"
                    }, {
                        label: "Python",
                        data : json.data_python,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#0f0",
                        pointColor: "#0f0",
                        pointStrokeColor: "#0f0"
                    }, {
                        label: "P4A",
                        data : json.data_p4a,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#00ff9a",
                        pointColor: "#00ff9a",
                        pointStrokeColor: "#00ff9a"
                    }, {
                        label: "Pys60",
                        data : json.data_pys60,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#008000",
                        pointColor: "#008000",
                        pointStrokeColor: "#008000"
                    }, {
                        label: "HTML",
                        data : json.data_html,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#ffc0cb",
                        pointColor: "#ffc0cb",
                        pointStrokeColor: "#ffc0cb"
                    }, {
                        label: "CSS",
                        data : json.data_css,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#ff1493",
                        pointColor: "#ff1493",
                        pointStrokeColor: "#ff1493"
                    }, {
                        label: "JS",
                        data : json.data_js,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#0ff",
                        pointColor: "#0ff",
                        pointStrokeColor: "#0ff"
                    }, {
                        label: "jQuery",
                        data : json.data_jq,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#afeeee",
                        pointColor: "#afeeee",
                        pointStrokeColor: "#afeeee"
                    }, {
                        label: "Angular",
                        data : json.data_angular,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#00f",
                        pointColor: "#00f",
                        pointStrokeColor: "#00f"
                    }, {
                        label: "SQL",
                        data : json.data_sql,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#f0f",
                        pointColor: "#f0f",
                        pointStrokeColor: "#f0f"
                    }, {
                        label: "Linux",
                        data : json.data_linux,
                        fillColor: "rgba(0,0,0,0)",
                        strokeColor: "#0",
                        pointColor: "#0",
                        pointStrokeColor: "#0"
                    }
                ]
            };

            var ctx = document.getElementById(
                    'canvas_docs_all_chartjs'
            ).getContext("2d");
            var line = new Chart(ctx).Line(
                    data,
                    {
                        legendTemplate: "" +
                    "<ul class=\"<%=name.toLowerCase()%>-legend\">" +
                    "<% for (var i=0; i<datasets.length; i++){" + "%>" +
                    "<li>" +
                    "<span style=\"color:<%=datasets[i].strokeColor%>\">" +
                    "<%if(datasets[i].label){" + "%>" +
                    "<%=datasets[i].label%><%" + "}%></span></li><%" + "}%></ul>"
                    });
            var div_legend = document.getElementById(
                    'div_legend_docs_all_chartjs');
            div_legend.innerHTML = line.generateLegend();
        }

        function createCharts(){
            $.getJSON("{% url 'metrics:data_month' %}", createDataMonthCharts);
            $.getJSON("{% url 'metrics:data_week' %}", createDataWeekCharts);
            $.getJSON("{% url 'metrics:docs_data_all' %}", createDocsAllCharts);

        }
        $(document).ready(function(){
            Chart.defaults.global.tooltipEvents = [];
            Chart.defaults.global.responsive = true;
            Chart.defaults.global.animation = false;
            createCharts();
        });
    </script>
{% endblock %}

{% block content %}

    <h3>Количество ip-адресов, которые побывали на сайте</h3>
    <div class="row">
        {# за месяц #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_ip_chartjs"></canvas>
        </div>
        {# неделя #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_ip_week_chartjs"></canvas>
        </div>
    </div>

    <h3>Количество уникальных ip-адресов, которые побывали на сайте</h3>
    <div class="row">
        {# месяц #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_ip_uniq_chartjs"></canvas>
        </div>
        {# неделя #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_ip_uniq_week_chartjs"></canvas>
        </div>
    </div>

    <h3>Количество просмотров страниц коспектов</h3>
    <div class="row">
        {# месяц #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_docs_chartjs"></canvas>
        </div>
        {# неделя #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_docs_week_chartjs"></canvas>
        </div>
    </div>

    <h3>Количество просмотров страниц блога</h3>
    <div class="row">
        {# месяц #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_blog_chartjs"></canvas>
        </div>
        {# неделя #}
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <canvas id="canvas_blog_week_chartjs"></canvas>
        </div>
    </div>

    <h3>Количество просмотров страниц конспектов по категориям</h3>
    <div class="row">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <div id="div_legend_docs_all_chartjs"></div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <canvas id="canvas_docs_all_chartjs"></canvas>
        </div>
    </div>
{% endblock %}